version: "3"
services:
  keycloak:
    image: jboss/keycloak
    ports:
    - "8080:8080"
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin123
    - KEYCLOAK_IMPORT=/tmp/realm.json
    - DB_VENDOR=postgres
    - DB_ADDR=keycloak-db
    - DB_PORT=5432
    - DB_USER=keycloak
    - DB_PASSWORD=password
    volumes:
    - ./keycloak/realm.json:/tmp/realm.json

  keycloak-db:
    image: postgres
    ports:
    - "65432:5432"
    environment:
    - POSTGRES_DB=keycloak
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=password
  
    