version: "3"
services:
  keycloak:
    image: jboss/keycloak
    ports:
    - "8080:8080"
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin123
    - KEYCLOAK_IMPORT=/tmp/realm.json
    - DB_VENDOR=h2
    volumes:
    - ./keycloak/realm.json:/tmp/realm.json
    